[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"
author = "lalit"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "zero2prod"

[dependencies]
actix-web = "^4.1.0"
actix-http = "^3.2.1"
actix-rt = "^2.7.0"
reqwest = "^0.11.11"
tokio = "^1.20.0"
